### ISSUE TITLE
Tela "Cancelar Documento Eletrônico" sem opção de criar novos registros diretamente

### ISSUE THREAD

**Issue by mstuttgart** [odoo-brazil/odoo-brazil-eletronic-documents#110]
Olá pessoal. Gostaria de sugerir a seguinte modificação:
- Deixar a tela `Localização Brazil->Fiscal->Cancelar Documento Eletrônico` sem a possibilidade de criar novos registros, de maneira semelhante a tela `Localização Brazil->Fiscal->Carta de Correção` deixando ambos apenas para gerenciamento dos eventos relacionados a NFe.

Deste modo, assim como ocorre com a carta, o cancelamento seria realizado apenas na _view_ da fatura. Isso diminuiria o custo de manter o cancelamento por duas vias diferentes (_view_ da NFe e _view_ Cancelar Documento Fiscal) e que funcionam da mesma maneira (uma nota por vez). Cancelar uma nota através da _view_ de "Cancelar Documento Fiscal" não apresenta muitas vantagens, uma vez que você tem de selecionar a fatura pelo nome (abrindo possibilidades para erro) e permite apenas o cancelamento de uma fatura por vez (igual ao que seria realizando pela _view_ da NFe). O cancelamento pela NFe se torna mais prático já que você tem todos os dados da fatura na tela para conferir antes de cancelá-la.

O que vocês acham? Por gentileza, me avisem caso tenha deixado escapar algum dado importante de uso do `Cancelar Documento Fiscal`.

@alexsandrohaag

Corrige problemas como o relatado em: https://github.com/odoo-brazil/odoo-brazil-eletronic-documents/issues/101

**Comment by mileo** [comment]
Concordo contigo, será que um dia seria preciso cancelar uma fatura, sem ter o registro account.invoice?

**Comment by danimaribeiro** [comment]
:+1:

**Comment by alexsandrohaag** [comment]
Concordo. Visto que já existe a função mais completa e funcional, não vejo porque manter esta.

**Comment by mstuttgart** [comment]
Resolve https://github.com/odoo-brazil/odoo-brazil-eletronic-documents/issues/101
