### ISSUE TITLE
Criação do branch 10.0

### ISSUE THREAD

**Issue by ghost** [odoo-brazil/odoo-brazil-eletronic-documents#119]
Estaremos migrando os módulos nfe e nfe_attach pelo que gostariamos de fazer os PRs para o branch 10.0.

Também gostaria de saber se têm intenções de passar este repositório para a OCA.

Obrigado!

**Comment by danimaribeiro** [comment]
Acho legal vocês lerem essas duas discussões:

https://github.com/OCA/l10n-brazil/pull/363
https://github.com/OCA/l10n-brazil/issues/402

Sou contra apenas migrar, devemos reescrever completamente esses módulos baseados em documentos eletrônicos.

**Comment by ghost** [comment]
Entendo a ideia, mas acontece que no final deste mês estaremos emitindo NF-e na versão 10, independentemente das mudanças que possam ocorrer no futuro.. 

Daí a criação do branch apenas para que todos tivessem conhecimento e acesso ao nosso trabalho (para que não fique apenas no nosso repositório). 

Se criar apenas é nesse sentido, para que quem quiser possa usar no formato atual. Caso decidam não criar então criaremos nós no nosso repositório sem o PR. 

Veja se pode criar ou não e deixe aqui o veredito por favor.

Grande abraço Danimar!

**Comment by mileo** [comment]
@carlosmaguda Pessoal vou acertar esse repo com as ultimas mudanças e criar a branch 10.0 com base nele. 
Vou precisar fazer alguns merges sem as devidas revisões de todos. Td bem?

Hoje deixo isso pronto.

CC: @mstuttgart @renatonlima @leorochael

**Comment by renatonlima** [comment]
@mileo 


Não vejo problema, eu diria que é apenas importante melhorar o código com os padrões da OCA pois esta semana já vai ser possivel passar esta branch para o repo Satellite da OCA

**Comment by ghost** [comment]
Ótimo! Obrigado @mileo @renatonlima @danimaribeiro

**Comment by mileo** [comment]
https://github.com/odoo-brazil/odoo-brazil-eletronic-documents/issues/127
