### ISSUE TITLE
Nome dos arquivos da NFe anexados

### ISSUE THREAD

**Issue by lepri** [odoo-brazil/odoo-brazil-eletronic-documents#12]
Ao enviar os arquivos da NFe, xml e pdf, para o cliente, o nome dos arquivos estão vindo sendo enviado apenas com as extensões no nome.

Por exemplo: o PDF está sendo enviado como .pdf e o XML está sendo enviado como .xml e não com o nome da chave da NFe + a extensão

**Comment by mileo** [comment]
Acabei de ter esse problema na 7.0, alguém + confirma esse issue?

**Comment by lepri** [comment]
Eu já tive esse problema mas não lembro como resolvi. Vou procurar e te mando

**Comment by lepri** [comment]
@mileo dá uma olhada nesse commit: https://github.com/lepri/nfe/commit/2e7635350be0b3819eb01a225e1f90210d349656

**Comment by danimaribeiro** [comment]
Corrigido nesse #73  ?

**Comment by lepri** [comment]
@danimaribeiro sim!
