### ISSUE TITLE
[Pergunta] NFS-e

### ISSUE THREAD

**Issue by brunocasado** [odoo-brazil/odoo-brazil-eletronic-documents#145]
Pessoal,

Poderiam me esclarecer se a nota fiscal de serviço está implementada? se sim quais municipios?

Grato!

**Comment by rvalyi** [comment]
Ola @brunocasado do lado da Akretion o plano eh propor de usar a lib da Trustcode https://github.com/danimaribeiro/PyTrustNFe na OCA para o Odoo 11+. Estamos ainda migrando para a v10 os modulos da OCA. Porem na v10 nao ha plano da nossa parte de aumentar o support de NFS-e na OCA. Nao ha biblioteca de nfse para Python de qualidade decente para ser usado na OCA com python 2.7 ou seja na versao 10 do Odoo. Por isso para ter um suporte na OCA teria que haver um backport da lib da Trustcode. Ou entao iniciativas com codigo porco mas isso fora da OCA entao.

**Comment by brunocasado** [comment]
Um rapaz aqui na empresa desenvolveu usando o serviço invoicy, porém acabou desenvolvendo no meio do código original. Isso está causando alguns transtornos pra gente. Mas mesmo assim obrigado @rvalyi
