### ISSUE TITLE
nfe_import gerando erro de instalação

### ISSUE THREAD

**Issue by chicocvenancio** [odoo-brazil/odoo-brazil-eletronic-documents#24]
Ao tentar instalar o nfe_import recebo o erro:
IOError: File not found: nfe_import/wizard/akretion_nfe_import_view.xml

**Comment by danimaribeiro** [comment]
Obrigado pelo bug, mas este módulo ainda não foi implementado.
Existe um PR com a funcionalidade de importação:
https://github.com/odoo-brazil/odoo-brazil-eletronic-documents/pull/23
Se puder testar agradecemos.
