### ISSUE TITLE
AttributeError: 'NFe200' object has no attribute 'import_edoc'

### ISSUE THREAD

**Issue by ATSTI** [odoo-brazil/odoo-brazil-eletronic-documents#45]
Erro quando clico em Importar :
   openerp.addons.nfe_import.wizard.l10n_br_account_invoice_import: 'NFe200' object has no attribute 'import_edoc'
Traceback (most recent call last):
  File "/opt/OCB/addons/nfe_import/wizard/l10n_br_account_invoice_import.py", line 80, in import_edoc
    eDoc = edoc_obj.import_edoc(
AttributeError: 'NFe200' object has no attribute 'import_edoc'

**Comment by danimaribeiro** [comment]
Acho que deve estar faltando esse PR aqui na localização:
https://github.com/odoo-brazil/l10n-brazil/pull/52

Muda para essa branch ali a localização.
