### ISSUE TITLE
Problemas ao Cancelar uma NFe no status sefaz_exception

### ISSUE THREAD

**Issue by renatonlima** [odoo-brazil/odoo-brazil-eletronic-documents#46]
Ao tentar cancelar uma nota que tenha dado erro na transmissão é chamada a função de cancelamento da Sefaz eu dei uma olhada https://github.com/odoo-brazil/odoo-brazil-eletronic-documents/blob/8.0/nfe/account_invoice.py#L223 ele compara se o campo nfe_status esta em branco, só que este campo esta com a string ' - ', por isso que a função chama o cancelamento da sefaz.

@mileo @danimaribeiro 

Se ainda não foi corrido isso eu posso subir a correção do campo nfe_status, mas uma sugestão, não seria melhor ao invés de conferir o campo do protocolo ao invés do nfe_status?

**Comment by danimaribeiro** [comment]
Também concordo que seja melhor verificar o protocolo.

**Comment by mileo** [comment]
:+1:

**Comment by danimaribeiro** [comment]
Fixed.
