### ISSUE TITLE
Versão 9

### ISSUE THREAD

**Issue by higorvaz** [odoo-brazil/odoo-brazil-eletronic-documents#90]
Prezados boa noite.
Existe já o desenvolvimento deste módulos para versão 9 do Odoo ?
Posso ajudar?
Atenciosamente,
Higor

**Comment by danimaribeiro** [comment]
Ainda não existe.
Tem que começar migrando a localização principal:
https://github.com/OCA/l10n-brazil

**Comment by higorvaz** [comment]
Certo, mas pelo que vi esta localização principal já possui um branch para versão 9, não estaria faltando apenas continuar a migração dos documentos fiscais ?

**Comment by mileo** [comment]
@higorvaz Da uma lida nisso: 

https://odoo-community.org/blog/oca-news-1/post/odoo-9-accounting-oca-28

Sem os problemas resolvidos investir na v9 é tempo perdido.
