### ISSUE TITLE
Erro ao Consultar o Sefaz

### ISSUE THREAD

**Issue by pauloneda** [odoo-brazil/odoo-brazil-eletronic-documents#99]
nfe/nfe/res_partner.py", line 45, in sefaz_check
    validate_nfe_configuration(company)
  File "/opt/odoo/nfe/nfe/sped/nfe/validator/config_check.py", line 56, in validate_nfe_configuration
    if not company.nfe_version:
AttributeError: 'int' object has no attribute 'nfe_version'

**Comment by FelipeLopes360** [comment]
Eu consegui realizar consulta normalmente.

**Comment by alexsandrohaag** [comment]
Paulo, no cadastro da empresa, na aba Fiscal - Produto - NFe, o que tem preenchido no campo "Versão da NFe"?

**Comment by pauloneda** [comment]
Versão NFe =  3.10
É um campo Select, isso que estranhei, estou verificando ainda este erro, pois algumas vezes consulta e não dá erro.

**Comment by alexsandrohaag** [comment]
Pela mensagem parece que está chegando como int o objeto "company". Deve estar ocorrendo alguma redefinição deste em algum momento.

**Comment by pauloneda** [comment]
Hoje olhando o código surgiu uma dúvida.
Clientes em Multi-Empresa o company_id em res_partner é nulo.

https://github.com/odoo-brazil/odoo-brazil-eletronic-documents/blob/8.0/nfe/models/res_partner.py#L38

**Comment by danimaribeiro** [comment]
Sim, já tinha notado este problema também.

**Comment by pauloneda** [comment]
Aqui funcionou com esta alteração

```
def sefaz_check(self):
    if not self.company_id:
        company_id = self.env.user.company_id
    else:
        company_id = self.company_id

    validate_nfe_configuration(company_id)
```
